name: Sync MCP Servers

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Sync awesome-mcp-servers
        run: |
          git submodule add https://github.com/punkpeye/awesome-mcp-servers.git .punkpeye/awesome-mcp-servers
          cd .punkpeye/awesome-mcp-servers
          git fetch --all
          git reset --hard origin/main
          cd ../..
          git add .punkpeye/awesome-mcp-servers
          git commit -m "chore: sync awesome-mcp-servers repository to subdirectory"
          git push
      - name: Git Push
        run: git push