name: Sync MCP Servers

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Sync modelcontextprotocol/servers
        run: |
          rm -rf .modelcontextprotocol/servers
          mkdir -p .modelcontextprotocol
          git clone https://github.com/modelcontextprotocol/servers.git .modelcontextprotocol/servers
          git add .modelcontextprotocol/servers
          git commit -m "chore: sync modelcontextprotocol/servers repository" || echo "No changes to commit"

      - name: Sync punkpeye/awesome-mcp-servers
        run: |
          rm -rf .punkpeye/awesome-mcp-servers
          mkdir -p .punkpeye
          git clone https://github.com/punkpeye/awesome-mcp-servers.git .punkpeye/awesome-mcp-servers
          git add .punkpeye/awesome-mcp-servers
          git commit -m "chore: sync punkpeye/awesome-mcp-servers repository" || echo "No changes to commit"

      - name: Sync wong2/awesome-mcp-servers
        run: |
          rm -rf .wong2/awesome-mcp-servers
          mkdir -p .wong2
          git clone https://github.com/wong2/awesome-mcp-servers.git .wong2/awesome-mcp-servers
          git add .wong2/awesome-mcp-servers
          git commit -m "chore: sync wong2/awesome-mcp-servers repository" || echo "No changes to commit"

      - name: Sync appcypher/awesome-mcp-servers
        run: |
          rm -rf .appcypher/awesome-mcp-servers
          mkdir -p .appcypher
          git clone https://github.com/appcypher/awesome-mcp-servers.git .appcypher/awesome-mcp-servers
          git add .appcypher/awesome-mcp-servers
          git commit -m "chore: sync appcypher/awesome-mcp-servers repository" || echo "No changes to commit"

      - name: Git Push
        run: git push